[package]
name = "starknet-event-query"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
eyre = "0.6.12"
glob = "0.3.3"
itertools = "0.14.0"
pretty_assertions_sorted = "1.2.3"
regex = "1.12.3"
serde_json = "1.0.150"
starknet-rust = "0.19.1"
starknet-rust-tokio-tungstenite = "0.19.1"
tempfile = "3.27.0"
time = { version = "0.3.47", features = ["parsing"] }
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "std", "time"] }

